name: AquaKoi
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.22.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.0.0
  firebase_database: ^11.0.0
  firebase_auth: ^5.0.0
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  getwidget: ^4.0.0
  image_picker: ^0.8.4+3
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  firebase_messaging: ^15.0.0
  firebase_core: ^3.0.0
  flutter_plugin_android_lifecycle: ^2.0.20  # Update to the latest version


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
    - family: Google Sans
      fonts: 
        - asset: assets/fonts/GoogleSansBold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSansRegular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSansItalic.ttf
          weight: 400
        - asset: assets/fonts/GoogleSansMedium.ttf
          weight: 500

